# frontend build stage
FROM node:22-alpine AS client-builder

WORKDIR /app

COPY ./client/package.json ./client/package-lock.json ./

RUN npm ci

COPY ./client/ .

ENV VITE_API_URL=/api VITE_UPLOADS_URL=/uploads

RUN npm run build


# nginx stage
FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# copying built frontend bundle to nginx
COPY --from=client-builder /app/dist /usr/share/nginx/html
